model:
    name: 'SemiSupCompletionModel'
    depth_net:
        name: 'PackNetSAN01'
        version: '1A'
        dropout: 0.5
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
        scale_output: 'top-center'
datasets:
    augmentation:
        crop_eval_borders: (-352, 0, 0.5, 1216)
    test:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['groundtruth']
save:
    folder: 'outputs/'
    depth:
        rgb: True
        viz: True
        npz: True
        png: True