model:
    name: 'SemiSupCompletionModel'
    loss:
        supervised_method: 'sparse-ssi'
        supervised_num_scales: 1
        supervised_loss_weight: 1.0
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001  # YOLOv8은 lower learning rate로 시작
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'YOLOv8SAN01'
        variant: 's'  # YOLOv8s (small) - 's', 'm', 'l', 'x' 중 선택
        dropout: 0.1
        # SAN 설정
        use_film: false
        film_scales: [0, 1, 2]  # 첫 3개 스케일에서 FiLM 적용
        use_enhanced_lidar: false
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
        scale_output: 'top-center'

datasets:
    augmentation:
        crop_train_borders: (-352, 0, 0.5, 1216)
        crop_eval_borders: (-352, 0, 0.5, 1216)
    train:
        batch_size: 4  # YOLOv8은 더 큰 모델이므로 배치 사이즈 조정
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_zhou_files_tiny.txt']
        input_depth_type: ['velodyne']
        depth_type: ['groundtruth']
        repeat: [1]
    validation:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        input_depth_type: ['velodyne','']
        depth_type: ['groundtruth','groundtruth']
    test:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        input_depth_type: ['velodyne']
        depth_type: ['groundtruth']

arch:
    seed: 42
    clip_grad: 10.0
    max_epochs: 30
    eval_during_training: true
    eval_progress_interval: 0.1
    eval_subset_size: 50

checkpoint:
    filepath: 'checkpoints/yolov8san01/'
    save_top_k: -1

save:
    folder: 'outputs/yolov8san01/'